### ISSUE TITLE
Bump `letsbuilda-pypi` and replace `requests` and `aiohttp` with `httpx`

### ISSUE THREAD

**Issue by shenanigansd** [vipyrsec/dragonfly-mainframe#148]
`letsbuilda-pypi==5.0.0` has been released with `httpx` support, which is the last thing keeping us from dropping `requests` and `aiohttp`.
Lets get it bumped so we can drop those dependencies.

**Comment by SomeHybrid** [comment]
can I be assigned to this issue? [birdo literally doesnt know he's assigned to this issue](https://discord.com/channels/267624335836053506/267624335836053506/1148107666254733342)
