### ISSUE TITLE
Accept rule match locations

### ISSUE THREAD

**Issue by jonathan-d-zhang** [vipyrsec/dragonfly-mainframe#227]
# Why?
This will be more helpful for debugging rules as well as providing more information for readers of our reports.

# What/How?
Add a JSON column to `scans` to hold all the match information. This will also make the `package_rules` and `rules` table irrelevant.

Also, the `POST /package` endpoint should be modified to use this new column, and the Pydantic model should be updated too.

**Comment by jonathan-d-zhang** [comment]
After further review, the schema for the match information will look like
```json
{
  "rulename": {
    "label": {
      "data": list[int],
      "range": {
        "end": int,
        "start": int
      }
    }
  }
}
```
which looks something like
```json
{
  "rule_name": {
    "$label": [
      {
        "data": [
          76,
          111,
          114,
          101,
          109,
          32,
          105,
          112,
          115,
          117,
          109
        ],
        "range": {
          "end": 11,
          "start": 0
        }
      }
    ]
  }
}

**Comment by Robin5605** [comment]
This will also be added into the database as a `JSONB` column. `package_rules` and `rules` table will be dropped.
