### ISSUE TITLE
Absorb reporting and deprecate dragonfly-reporter

### ISSUE THREAD

**Issue by shenanigansd** [vipyrsec/dragonfly-mainframe#252]
[dragonfly-reporter](https://github.com/vipyrsec/dragonfly-reporter) abstracts a single API call into an entire microservice. This adds unnecessary maintenance burden and causes complexity when trying to understand where an error originated from.
The single API call can be handled directly by the Mainframe itself, and the reporter microservice can be archived.

**Comment by BruDriguezz** [comment]
👋 I'd like to take this
