### ISSUE TITLE
Kill stats endpoints and just make them in grafana

### ISSUE THREAD

**Issue by jonathan-d-zhang** [vipyrsec/dragonfly-mainframe#314]
Currently the metrics we expose are just database queries, nothing that needs to be done on mainframe. Just make these in Grafana directly.

**Comment by Robin5605** [comment]
Is it better to use Grafana's Postgres integration to get our data from the database, or is it better to use Prometheus? 

For instance, I believe it is possible to make a query to graph packages ingested over time, but it may be easier to have a Prometheus [counter](https://prometheus.io/docs/concepts/metric_types/#counter) that increments inside the queue package endpoint. Graphing a counter over time is very common and Grafana has PromQL query presets for this.
