### ISSUE TITLE
Allow reporting on quarantined packages

### ISSUE THREAD

**Issue by Robin5605** [vipyrsec/dragonfly-mainframe#319]
The PyPI JSON API returns a 404 for quarantined projects ([source here](https://github.com/pypi/warehouse/blob/1b33b28f078256f40069919c565331abb71de4fd/warehouse/packaging/utils.py#L32-L37)), which makes the `_validate_pypi` check fail with a 404
https://github.com/vipyrsec/dragonfly-mainframe/blob/14edb7d5a294d0a03f3da316b4889007316e3d85/src/mainframe/endpoints/report.py#L141-L149

However, the HTTP endpoint will still return a 200, and we still want to be able to report quarantined packages to help PyPI administrators triage quarantined packages faster. I propose that if the JSON endpoint returns a 404, we then make a GET request to the HTTP endpoint to see if we get a 200. If we do, then the package is quarantined and the `_validate_pypi` check should pass, allowing a report.

**Comment by jonathan-d-zhang** [comment]
Could we just only request the HTML page?

**Comment by Robin5605** [comment]
Didn't think of that, yes that sounds better
