### ISSUE TITLE
Add pagination for `GET /package`

### ISSUE THREAD

**Issue by jonathan-d-zhang** [vipyrsec/dragonfly-mainframe#91]
# Problem
Currently, this endpoint simply returns all releases matching the query criteria. This is nice and simple, but struggles for queries with larger result sets.
# Solution
Pagination! We have a few choices for how we implement this.
- https://pypi.org/project/fastapi-pagination/ we can try this. I've never used or heard about it.
- We can implement our own pagination. We would need to decide what kid of pagination we want (offset vs cursor).

**Comment by BruDriguezz** [comment]
Hey, I'd like to take this!
